from __future__ import annotations

import sys
from pathlib import Path

import rich_click as click

from .config import load_test_configs
from .failover.run import run_failover_profile, run_failover_simple
from .load_runner import LoadSearchError, run_load_test
from .trex.run.simple import CapturedTcpPacket, SimpleTcpTestResult, run_simple_tcp_test
from .trex.run.udp import run_udp_test
from .trex.setup import setup_trex_server


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
def app() -> None:
    """Host-side NAT benchmark orchestration."""


@app.group("setup")
def setup_group() -> None:
    """Deploy benchmark runtime components."""


@setup_group.command("trex")
def setup_trex_command() -> None:
    """Deploy TRex server for the current VPP memif topology."""
    setup_trex_server()


@app.group("trex")
def trex_group() -> None:
    """Run TRex-based benchmark workflows."""


@trex_group.group("run")
def trex_run_group() -> None:
    """Run TRex traffic tests."""


@trex_run_group.command("udp")
@click.option(
    "--target-pps",
    type=int,
    required=True,
    help="Target UDP packets per second. Example: 100000 or 1000000.",
)
@click.option(
    "--duration",
    type=float,
    required=True,
    help="Test duration in seconds. Example: 10 or 30.5.",
)
@click.option(
    "--flow-count",
    type=int,
    default=1,
    show_default=True,
    help="Number of UDP flows generated by varying source port.",
)
@click.option(
    "--warmup-sec",
    type=float,
    default=0,
    show_default=True,
    help="Warmup duration before counters are cleared and measurement starts.",
)
def trex_run_udp_command(target_pps: int, duration: float, flow_count: int, warmup_sec: float) -> None:
    """Run UDP traffic through the current TRex/VPP topology."""
    loss_percent = run_udp_test(
        target_pps=target_pps,
        duration=duration,
        flow_count=flow_count,
        warmup_sec=warmup_sec,
    )
    click.echo(f"Loss Percent:")
    click.echo(f"{loss_percent:.6f}")


@app.group("run")
def run_group() -> None:
    """Run functional checks from the host."""


@run_group.command("simple")
def run_simple_command() -> None:
    """Run a minimal TCP NAT correctness check."""
    print_simple_tcp_result(run_simple_tcp_test())


@run_group.command("load")
@click.option(
    "--load-config",
    "--config",
    type=click.Path(path_type=Path, dir_okay=False),
    help="Path to load YAML config. Defaults to configs/loadtest/load/test_config.yaml.",
)
@click.option(
    "--search-config",
    type=click.Path(path_type=Path, dir_okay=False),
    help="Path to search YAML config. Defaults to configs/loadtest/search/test_config.yaml.",
)
def run_load_command(
    load_config: Path | None,
    search_config: Path | None,
) -> None:
    """Run TRex PPS boundary search."""
    resolved_config, search, load_config_path, search_config_path = load_test_configs(load_config, search_config)
    try:
        run_load_test(
            resolved_config,
            search,
            load_config_path,
            search_config_path,
        )
    except LoadSearchError as exc:
        raise click.ClickException(str(exc)) from exc


@run_group.group("failover")
def run_failover_group() -> None:
    """Run VPP restart failover checks."""


@run_failover_group.command("simple")
def run_failover_simple_command() -> None:
    """Prepare and run the simple UDP failover scenario."""
    run_failover_simple()


@run_failover_group.command("profile")
def run_failover_profile_command() -> None:
    """Run the profile failover scenario."""
    run_failover_profile()


def print_simple_tcp_result(result: SimpleTcpTestResult) -> None:
    """Печатает результат минимальной TCP-проверки NAT."""
    click.echo(f"NAT: {format_nat_status(result.nat_applied)}")
    click.echo(result.verdict)

    if not result.captured_packets:
        click.echo("Packets: <empty>")
        return
    for packet in result.captured_packets:
        print_captured_tcp_packet(packet)


def format_nat_status(nat_applied: bool | None) -> str:
    """Форматирует короткий статус NAT для CLI."""
    if nat_applied is True:
        return "works"
    if nat_applied is False:
        return "does not work"
    return "unknown"


def print_captured_tcp_packet(packet: CapturedTcpPacket) -> None:
    """Печатает только адреса и порты TCP-пакета."""
    src = format_endpoint(packet.ip_src, packet.tcp_src_port)
    dst = format_endpoint(packet.ip_dst, packet.tcp_dst_port)
    click.echo(f"Packet: {src} -> {dst}")


def format_endpoint(ip: str | None, port: int | None) -> str:
    """Форматирует `ip:port`, сохраняя пустые значения читаемыми."""
    rendered_ip = ip or "?"
    rendered_port = str(port) if port is not None else "?"
    return f"{rendered_ip}:{rendered_port}"


def main() -> int:
    try:
        app.main(standalone_mode=False)
        return 0
    except click.ClickException as exc:
        exc.show()
        return exc.exit_code
    except (OSError, RuntimeError, ValueError) as exc:
        click.echo(f"error: {exc}", err=True)
        return 1
    except click.Abort:
        click.echo("Aborted", err=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
