#cloud-config
hostname: external-vm
fqdn: external-vm.local

users:
  - name: zero
    gecos: Ubuntu User
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [sudo]
    lock_passwd: false
    plain_text_passwd: "orez1234"
    shell: /bin/bash

ssh_pwauth: false
disable_root: true
ssh_deletekeys: false

write_files:
  - path: /etc/modules-load.d/9p.conf
    owner: root:root
    permissions: '0644'
    content: |
      9p
      9pnet
      9pnet_virtio

bootcmd:
  - mkdir -p /mnt/host

runcmd:
  - modprobe 9p || true
  - modprobe 9pnet || true
  - modprobe 9pnet_virtio || true
  - mount /mnt/host || true

mounts:
  - [hostshare, /mnt/host, 9p, "trans=virtio,version=9p2000.L,rw,nofail,_netdev", "0", "0"]
