#cloud-config
hostname: external-vm
fqdn: external-vm.local

users:
  - name: zero
    gecos: Ubuntu User
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [sudo]
    lock_passwd: false
    plain_text_passwd: "orez1234"

ssh_pwauth: false
disable_root: true
